dist: trusty
sudo: required
language: node_js

node_js:
  - "9"

install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install

cache:
  directories:
    - node_modules

env:
  - SOLIDITY_COVERAGE=true


matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true

before_script:
  - truffle version
  - npm run rpc > /dev/null &
  - sleep 5

script:
  - npm run lint
  - npm run lint:contract
  - npm run test

  after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls

notifications:
  email:
    on_success: never
    on_failure: always
  slack: powerpiper:fEBF3prSwdbMzHrmXs6Pd4ut
