module.exports = {
  TOKEN_NAME: 'TOK',
  SITE_TITLE: 'Token Starter',
  MINIMUM_CONTRIBUTION: 0.1,
  MINIMUM_GAS: 27000,
  BTC_CONTRIBUTION_ADDRESS: 'btc_test',
  LTC_CONTRIBUTION_ADDRESS: 'ltd_test',
  GA: 'UA-XXXXXXXX'
}
